import {
  Shield,
  ShieldCheck,
  LayoutDashboard,
  Activity,
  Bell,
  BellRing,
  Users,
  Settings,
  Heart,
  HeartPulse,
  Droplet,
  Thermometer,
  Footprints,
  Sparkles,
  TrendingUp,
  TrendingDown,
  Minus,
  Plus,
  PlusCircle,
  Pencil,
  Trash2,
  Check,
  CheckCircle,
  X,
  XCircle,
  AlertTriangle,
  AlertCircle,
  Info,
  Copy,
  Lock,
  Eye,
  EyeOff,
  Menu,
  PanelLeftClose,
  PanelLeftOpen,
  Clock,
  Calendar,
  Pill,
  Mail,
  LogOut,
  Inbox,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  User,
  Link,
  RotateCw,
  Loader2,
  Zap,
  Flame,
  Download,
  Printer,
  FileText,
  RotateCcw,
  Send,
  MailCheck,
  CalendarCheck,
  Circle,
  type LucideProps,
} from 'lucide-react';

const ICONS: Record<string, React.ComponentType<LucideProps>> = {
  shield: Shield,
  'shield-check': ShieldCheck,
  'layout-dashboard': LayoutDashboard,
  activity: Activity,
  bell: Bell,
  'bell-ring': BellRing,
  users: Users,
  settings: Settings,
  heart: Heart,
  'heart-pulse': HeartPulse,
  droplet: Droplet,
  thermometer: Thermometer,
  footprints: Footprints,
  sparkles: Sparkles,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  minus: Minus,
  plus: Plus,
  'plus-circle': PlusCircle,
  pencil: Pencil,
  'trash-2': Trash2,
  check: Check,
  'check-circle': CheckCircle,
  x: X,
  'x-circle': XCircle,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  info: Info,
  copy: Copy,
  lock: Lock,
  eye: Eye,
  'eye-off': EyeOff,
  menu: Menu,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  clock: Clock,
  calendar: Calendar,
  pill: Pill,
  mail: Mail,
  'log-out': LogOut,
  inbox: Inbox,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  user: User,
  link: Link,
  'rotate-cw': RotateCw,
  'loader-2': Loader2,
  zap: Zap,
  flame: Flame,
  download: Download,
  printer: Printer,
  'file-text': FileText,
  'rotate-ccw': RotateCcw,
  send: Send,
  'mail-check': MailCheck,
  'calendar-check': CalendarCheck,
  circle: Circle,
};

export interface IconProps extends Omit<LucideProps, 'ref'> {
  name: string;
}

export function Icon({ name, ...rest }: IconProps) {
  const Cmp = ICONS[name];
  if (!Cmp) return null;
  return <Cmp {...rest} />;
}
